require("user.cmp")
require("user.lsp")
require("user.keymaps")
require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.nvim-tree")
require("user.toggleterm")
require("user.neoscroll")
require("user.lualine")
require("user.bufferline")
require("user.trouble")
require("user.gitsigns")
-- require("user.ufo")
-- require("user.markdown-preview")
-- require("user.rust-tools")
-- require("user.coc-config")
-- require("user.code-runner")
-- require("user.competitest")
